char input(void);
int busca_ddd(int busca);
int busca_num(int tam, char celular[]);
int bissexto(int ano);
int data_int(int dia, int mes, int ano);
int data_str(char data[]);
int valida_cel(char celular[]);
int valida_cpf(char *cpf);
int valida_email(char email[]);
int valida_dig(char dig[]);
void espera();
//int valida_float(float dinheiro);
